### ISSUE TITLE
Any chance to provide the source code for RPi3/4 migration ?

### ISSUE THREAD

**Issue by 2ndTaleStudio** [stahlnow/amiga_drive#1]
Hi there,

you dis an amazing job by providing this application and toolset to the Amiga Lovers like I'd call myself though ;). However, I was wondering whether you would see a change to provide the ource code of your RPi kernel to enable others - like myself - to port it to other RPi version like the RPi3 B+ or RPi-Zero or even RPi4.

Thanks in advance for any response.

**Comment by stahlnow** [comment]
I didn't write the software, this is just a PCB based on the original project by Maurizio Ramondo, please see the link in the README.
